### ISSUE TITLE
[chore] Setup `forge fmt`

### ISSUE THREAD

**Issue by kaihiroi** [metacontract/mc#62]
## Type

- [x] Code Style/Formatting

## Description

Setting-up `forge fmt` to automate the formatting of Solidity code. This will ensure consistent code style and improve development efficiency.

## Tasks

- [x] setup `forge fmt`
- [x] setup editor setting
- [x] format all files
